doctrine:
    dbal:
        use_savepoints: true
        url: '%env(resolve:DATABASE_URL)%'
        charset: 'utf8mb4'
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_mapping: true
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: 'doctrine.orm.naming_strategy.underscore_number_aware'
        mappings:
            App:
                is_bundle: false
                type: 'attribute'
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: 'App'
        controller_resolver:
            auto_mapping: false
        dql:
            datetime_functions:
                timestampdiff: 'DoctrineExtensions\Query\Mysql\TimestampDiff'
                year: 'DoctrineExtensions\Query\Mysql\Year'
                month: 'DoctrineExtensions\Query\Mysql\Month'
                date: 'DoctrineExtensions\Query\Mysql\Date'
                now: 'DoctrineExtensions\Query\Mysql\Now'

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: 'pool'
                pool: 'doctrine.system_cache_pool'
            result_cache_driver:
                type: 'pool'
                pool: 'doctrine.result_cache_pool'
