framework:
    mailer:
        transports:
            main: '%env(MAILER_DSN)%'
            mailing: '%env(MAILING_MAILER_DSN)%'

when@test:
    framework:
        mailer:
            transports:
                main: 'null://null'
                mailing: 'null://null'
