monolog:
    channels:
        - 'deprecation'

when@dev:
    monolog:
        channels: [ 'queue' ]
        handlers:
            queues:
                type: 'rotating_file'
                path: '%kernel.logs_dir%/%kernel.environment%_queues.log'
                level: 'debug'
                max_files: 10
                channels: 'queue'
            main:
                type: 'rotating_file'
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: 'debug'
                max_files: 10
                channels: [ '!event' ]
            console:
                type: 'console'
                process_psr_3_messages: false
                channels: [ '!event', '!doctrine', '!console' ]

when@test:
    monolog:
        channels: [ 'queue' ]
        handlers:
            queues:
                type: 'rotating_file'
                path: '%kernel.logs_dir%/%kernel.environment%_queues.log'
                level: 'debug'
                max_files: 1
                channels: 'queue'
            main:
                type: 'fingers_crossed'
                action_level: 'error'
                handler: 'nested'
                excluded_http_codes: [ 404, 405 ]
                channels: [ '!event' ]
            nested:
                type: 'rotating_file'
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: 'debug'
                max_files: 1

when@prod:
    monolog:
        channels: [ 'queue' ]
        handlers:
            queues:
                type: 'rotating_file'
                path: '%kernel.logs_dir%/%kernel.environment%_queues.log'
                level: 'debug'
                max_files: 30
                channels: 'queue'
            main:
                type: 'fingers_crossed'
                action_level: 'error'
                handler: 'nested'
                channels: [ '!deprecation' ]
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50
            nested:
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                type: 'rotating_file'
                level: 'debug'
                channels: [ '!deprecation' ]
                max_files: 30
            console:
                process_psr_3_messages: false
                type: console
                channels: [ '!event', '!doctrine' ]
            deprecation:
                type: 'stream'
                channels: [ 'deprecation' ]
                path: 'php://stderr'
                formatter: 'monolog.formatter.json'
