imports:
    - { resource: 'services/admins.yaml' }

parameters:
    default_locale:             '%env(string:DEFAULT_LOCALE)%'
    project_web_title:          '%env(string:PROJECT_WEB_TITLE)%'
    project_url_base:           '%env(string:PROJECT_BASE_URL)%'
    project_backend_title:      '%env(string:PROJECT_BACKEND_TITLE)%'
    project_export_filename:    '%env(string:PROJECT_EXPORT_FILENAME_BASE)%'
    project_discount_extra_son: '%env(int:PROJECT_DISCOUT_PER_EXTRA_SON)%'
    google_tag_manager_enabled: '%env(bool:GOOGLE_TAG_MANAGER_IS_ENABLED)%'
    google_tag_manager_account: '%env(string:GOOGLE_TAG_MANAGER_ACCOUNT)%'
    google_analytics_enabled:   '%env(bool:GOOGLE_ANALYTICS_IS_ENABLED)%'
    google_analytics_account:   '%env(string:GOOGLE_ANALYTICS_ACCOUNT)%'
    google_maps_api_key:        '%env(string:GOOGLE_MAPS_API_KEY)%'
    google_calendar_api_key:    '%env(string:GOOGLE_CALENDAR_API_KEY)%'
    mailchimp_api_key:          '%env(string:MAILCHIMP_API_KEY)%'
    mailchimp_list_id:          '%env(string:MAILCHIMP_LIST_ID)%'
    facebook_pixel_enabled:     '%env(bool:FACEBOOK_PIXEL_ENABLED)%'
    facebook_pixel_id:          '%env(string:FACEBOOK_PIXEL_ID)%'
    facebook_api_key:           '%env(string:FACEBOOK_API_KEY)%'
    facebook_api_secret:        '%env(string:FACEBOOK_API_SECRET)%'
    boss_name:                  '%env(string:BOSS_NAME)%'
    boss_dni:                   '%env(string:BOSS_DNI)%'
    boss_phone_number_1:        '%env(string:BOSS_PHONE_NUMBER_1)%'
    boss_phone_number_2:        '%env(string:BOSS_PHONE_NUMBER_2)%'
    boss_address:               '%env(string:BOSS_ADDRESS)%'
    boss_city:                  '%env(string:BOSS_CITY)%'
    iban_business:              '%env(string:IBAN_BUSINESS)%'
    bic_number:                 '%env(string:BIC_NUMBER)%'
    mailer_destination:         '%env(string:MAILER_DESTINATION)%'
    delivery_dev_address:       '%env(string:DEV_DELIVERY_ADDRESS)%'
    admin_color:                '%env(string:ADMIN_COLOR)%'
    admin_tag_version:          '508007'
    admin_is_stage:             '%env(bool:ADMIN_IS_STAGE)%'
    mailing_per_day_limit:      '%env(int:MAILING_PER_DAY_LIMIT)%'
    preregister_period_is_open: false

services:
    _defaults:
        autowire: true
        autoconfigure: true
    # Commons
    App\:
        resource: '../src/'
    # Renamed Alises
    Qipsius\TCPDFBundle\Controller\TCPDFController: '@qipsius.tcpdf'
    # Template Blocks
    App\Block\EventCalendarBlock:
        arguments:
            - '@twig'
        tags:
            - { name: 'sonata.block' }
    App\Block\ChartsBlock:
        arguments:
            - '@twig'
            - '@App\Service\ChartsFactoryService'
        tags:
            - { name: 'sonata.block' }
    # Menus
    app.backend_top_nav_menu:
        class: 'Knp\Menu\MenuItem'
        factory: [ '@App\Menu\BackendTopNavMenuBuilder', 'createTopNavMenu' ]
        tags:
            - { name: 'knp_menu.menu', alias: 'backend_top_nav_menu' }
    app.backend_students_menu:
        class: 'Knp\Menu\MenuItem'
        factory: [ '@App\Menu\BackendStudentsMenuBuilder', 'createSideMenu' ]
        arguments:
            - '@request_stack'
        tags:
            - { name: 'knp_menu.menu', alias: 'backend_students_menu' }
    app.backend_invoice_menu:
        class: 'Knp\Menu\MenuItem'
        factory: [ '@App\Menu\BackendInvoiceMenuBuilder', 'createSideMenu' ]
        arguments:
            - '@request_stack'
        tags:
            - { name: 'knp_menu.menu', alias: 'backend_invoice_menu' }
    app.backend_files_manager_menu:
        class: 'Knp\Menu\MenuItem'
        factory: [ '@App\Menu\BackendFilesManagerMenuBuilder', 'createSideMenu' ]
        arguments:
            - '@request_stack'
        tags:
            - { name: 'knp_menu.menu', alias: 'backend_files_manager_menu' }
    app.frontend_top_menu:
        class: 'Knp\Menu\MenuItem'
        factory: [ '@App\Menu\FrontendMenuBuilder', 'createTopMenu' ]
        arguments:
            - '@request_stack'
        tags:
            - { name: 'knp_menu.menu', alias: 'top' }
